# Cookiecutter configuration used to bake Ada's webiste
default_context:
  project_directory: "hpkio-baked"
  author_name: "Ada Wright"
  author_email: "ada@hpk.io"
  project_short_name: "Ada's little website"
  project_codename: "hpk.io"
  project_module_name: "hpk"
  project_database_name: "hpkio"
  local_dev_hostname: "hpkio.local"
  production_hostname: "hpk.io"
  low_develop_port: "8071"
	project_github_url: "https://github.com/hipikat/hpk.io"
  docker_build_target: "ubuntu:focal"
	open_source_license: "BSD 2-clause"

abbreviations:
  pdjn: /Users/hipikat/dev/pdjn-cookiecutter
